FROM ubuntu:16.04
MAINTAINER zcl "173302591@qq.com"
RUN apt-get update -y && \  
    apt-get install -y python3-pip python3-dev
RUN mkdir -p ~/.pip
COPY pip.conf ~/.pip/pip.conf
COPY . /
WORKDIR /
RUN pip3 install -r requirements.txt
ENTRYPOINT [ "python3" ]
CMD [ "app/app.py" ]